service: mypay-customers

plugins:
    - serverless-bundle
    - serverless-plugin-tracing

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-1
    timeout: 30
    tracing:
        apiGateway: true
        lambda: true
    aliasStage:
        loggingLevel: 'ERROR'
        dataTraceEnabled: true
    environment:
        REGION: eu-west-1
        COGNITO_USER_POOL_ID: ${ssm:/cp/${self:custom.infraStage}/cp/CognitoUserPoolId}
        INFRA_STAGE: ${self:custom.infraStage}
        DB_RESOURCE_ARN: ${ssm:/cp/${self:custom.infraStage}/cp/DbClusterArn}
        SECRET_ARN: ${ssm:/cp/${self:custom.infraStage}/cp/SecretManagerArn}

    iamRoleStatements:
        - Effect: Allow
          Action:
              - rds-data:ExecuteStatement
              - rds-data:BatchExecuteStatement
              - rds-data:BeginTransaction
              - rds-data:CommitTransaction
              - rds-data:RollbackTransaction
          Resource: '*'
        - Effect: Allow
          Action:
              - secretsmanager:GetSecretValue
          Resource:
              'Fn::ImportValue': SecretManagerArn
        - Effect: 'Allow' # xray permissions
          Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
          Resource:
              - '*'

package:
    artifact: ${opt:artifact, ""}

custom:
    baseApiPath: api/v1
    defaultStage: dev
    stage: ${opt:stage, self:custom.defaultStage}
    infraStage: ${opt:infraStage, self:custom.defaultStage}

    customersEntityPath: ${self:custom.baseApiPath}/customers

    bundle:
        externals:
            - mypay-helpers
            - models
        linting: false #Ignore for compilation
        ignorePackages:
            - pg-hstore
            # only on aws
            - ../../../layers/helper_lib/src
            - ../../../layers/models_lib/src
            - ../../../../layers/helper_lib/src
            - ../../../../layers/models_lib/src
            - ../../layers/helper_lib/src

functions:
    - ${file(functions.yml)}
resources:
    # API Gateway Errors
    - ${file(api-gateway-errors.yml)}
