export const DocumentTypesId = {
    BANK_STATEMENT: 1,
    BUSINESS_RATES_BILL: 2,
    DRIVING_LICENCE: 3,
    PASSPORT: 4,
    RENTAL_AGREEMENT: 5,
    RESIDENCY_PERMIT: 6,
    UTILITY_BILL: 7,
    VOID_CHEQUE: 8,
    ID_PROOF_FRONT: 9,
    ID_PROOF_BACK: 10,
    BUSINESS_REGISTRATION_CERTIFICATE: 11
};
