export const DocumentStatusToName = {
    ACTIVE: 'ACTIVE',
    NEED_APPROVAL: 'NEED_APPROVAL',
    REJECTED: 'REJECTED',
    DELETED: 'DELETED',
    OLD: 'OLD',
    OVERRIDDEN: 'OVERRIDDEN',
    MISSING: 'MISSING'
};
