service: mypay-payments

plugins:
    - serverless-bundle
    - serverless-plugin-tracing

provider:
    name: aws
    runtime: nodejs12.x
    region: eu-west-1
    timeout: 30
    tracing:
        apiGateway: true
        lambda: true
    aliasStage:
        loggingLevel: 'ERROR'
        dataTraceEnabled: true
    environment:
        REGION: eu-west-1
        COGNITO_USER_POOL_ID: ${ssm:/cp/${self:custom.infraStage}/cp/CognitoUserPoolId}
        INFRA_STAGE: ${self:custom.infraStage}
        DB_RESOURCE_ARN: ${ssm:/cp/${self:custom.infraStage}/cp/DbClusterArn}
        SECRET_ARN: ${ssm:/cp/${self:custom.infraStage}/cp/SecretManagerArn}
        DATMAN_SES_HANDLER_API_KEY: ${ssm:/cp/${self:custom.infraStage}/cp/DatmanSesHandlerApiKey}
        GATEWAY_MESSAGING_ENDPOINT: ${ssm:/cp/${self:custom.infraStage}/cp/GatewayMessagingEndpoint}
        STRIPE_CREDENTIALS: ${ssm:/cp/${self:custom.infraStage}/cp/stripe_credentials}
        DATMAN_API_ENDPOINT: ${ssm:/cp/${self:custom.infraStage}/cp/datman_api_endpoint}
        DNA_REPORTING_API_ENDPOINT: ${ssm:/cp/${self:custom.infraStage}/cp/DNAReportingApiEndPoint}
        DNA_SCOPE: ${ssm:/cp/${self:custom.infraStage}/cp/DNAScope}
        DNA_CLIENT_SECRET: ${ssm:/cp/${self:custom.infraStage}/cp/DNACientSecret}
        DNA_CLIENT_ID: ${ssm:/cp/${self:custom.infraStage}/cp/DNAClientId}
        DNA_GRANT_TYPE: ${ssm:/cp/${self:custom.infraStage}/cp/DNAGrantType}

    iamRoleStatements:
        - Effect: Allow
          Action:
              - rds-data:ExecuteStatement
              - rds-data:BatchExecuteStatement
              - rds-data:BeginTransaction
              - rds-data:CommitTransaction
              - rds-data:RollbackTransaction
          Resource: '*'
        - Effect: Allow
          Action:
              - secretsmanager:GetSecretValue
          Resource:
              'Fn::ImportValue': SecretManagerArn
        - Effect: 'Allow' # xray permissions
          Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
          Resource:
              - '*'
        - Effect: Allow
          Action:
              - ses:*
              - ssm:GetParameters
              - sqs:listQueues
              - sqs:getQueueAttributes
              - sqs:receiveMessage
              - sqs:deleteMessage
              - sqs:sendMessage
          Resource: '*'

package:
    artifact: ${opt:artifact, ""}

custom:
    baseApiPath: api/v1
    defaultStage: dev
    stage: ${opt:stage, self:custom.defaultStage}
    infraStage: ${opt:infraStage, self:custom.defaultStage}

    paymentEntityPath: ${self:custom.baseApiPath}/payments

    bundle:
        externals:
            - mypay-helpers
            - models
        linting: false #Ignore for compilation
        ignorePackages:
            - pg-hstore
            # only on aws
            - ../../../layers/helper_lib/src
            - ../../../layers/models_lib/src
            - ../../../../layers/helper_lib/src
            - ../../../../layers/models_lib/src

functions:
    - ${file(functions.yml)}
resources:
    # API Gateway Errors
    - ${file(api-gateway-errors.yml)}
